/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceGeneratingRouteImport } from './routes/workspace.generating'
import { Route as ResultsTableRouteImport } from './routes/results.table'
import { Route as ResultsLetterRouteImport } from './routes/results.letter'
import { Route as ResultsEditRouteImport } from './routes/results.edit'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceGeneratingRoute = WorkspaceGeneratingRouteImport.update({
  id: '/workspace/generating',
  path: '/workspace/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsTableRoute = ResultsTableRouteImport.update({
  id: '/results/table',
  path: '/results/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsLetterRoute = ResultsLetterRouteImport.update({
  id: '/results/letter',
  path: '/results/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsEditRoute = ResultsEditRouteImport.update({
  id: '/results/edit',
  path: '/results/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/history': typeof HistoryRoute
  '/results/edit': typeof ResultsEditRoute
  '/results/letter': typeof ResultsLetterRoute
  '/results/table': typeof ResultsTableRoute
  '/workspace/generating': typeof WorkspaceGeneratingRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/history': typeof HistoryRoute
  '/results/edit': typeof ResultsEditRoute
  '/results/letter': typeof ResultsLetterRoute
  '/results/table': typeof ResultsTableRoute
  '/workspace/generating': typeof WorkspaceGeneratingRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/history': typeof HistoryRoute
  '/results/edit': typeof ResultsEditRoute
  '/results/letter': typeof ResultsLetterRoute
  '/results/table': typeof ResultsTableRoute
  '/workspace/generating': typeof WorkspaceGeneratingRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/history'
    | '/results/edit'
    | '/results/letter'
    | '/results/table'
    | '/workspace/generating'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/history'
    | '/results/edit'
    | '/results/letter'
    | '/results/table'
    | '/workspace/generating'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/history'
    | '/results/edit'
    | '/results/letter'
    | '/results/table'
    | '/workspace/generating'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  HistoryRoute: typeof HistoryRoute
  ResultsEditRoute: typeof ResultsEditRoute
  ResultsLetterRoute: typeof ResultsLetterRoute
  ResultsTableRoute: typeof ResultsTableRoute
  WorkspaceGeneratingRoute: typeof WorkspaceGeneratingRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/generating': {
      id: '/workspace/generating'
      path: '/workspace/generating'
      fullPath: '/workspace/generating'
      preLoaderRoute: typeof WorkspaceGeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/table': {
      id: '/results/table'
      path: '/results/table'
      fullPath: '/results/table'
      preLoaderRoute: typeof ResultsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/letter': {
      id: '/results/letter'
      path: '/results/letter'
      fullPath: '/results/letter'
      preLoaderRoute: typeof ResultsLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/edit': {
      id: '/results/edit'
      path: '/results/edit'
      fullPath: '/results/edit'
      preLoaderRoute: typeof ResultsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  HistoryRoute: HistoryRoute,
  ResultsEditRoute: ResultsEditRoute,
  ResultsLetterRoute: ResultsLetterRoute,
  ResultsTableRoute: ResultsTableRoute,
  WorkspaceGeneratingRoute: WorkspaceGeneratingRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
